-- Add final 10 exercises: Emotional Regulation to complete library of 50

INSERT INTO public.exercises (title, description, duration, category, tags, steps) VALUES

-- Emotional Regulation Exercises (10)
('54321 Grounding Technique', 'Use your senses to anchor yourself when feeling overwhelmed.', '5 minutes', 'Emotional Regulation', ARRAY['grounding', 'anxiety', 'panic'],
'[{"stepNumber":1,"title":"Five things you see","content":"Look around and name 5 things you can see. Say them out loud if possible.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Four things you touch","content":"Notice 4 things you can feel. The chair, your clothes, the temperature, the floor.","inputRequired":true,"inputType":"text"},{"stepNumber":3,"title":"Three things you hear","content":"Listen carefully. Name 3 sounds, even subtle ones.","inputRequired":true,"inputType":"text"},{"stepNumber":4,"title":"Two things you smell","content":"Identify 2 scents in your environment.","inputRequired":true,"inputType":"text"},{"stepNumber":5,"title":"One thing you taste","content":"Notice one taste in your mouth right now.","inputRequired":true,"inputType":"text"}]'),

('Opposite Action', 'Act opposite to a destructive emotional urge to change the emotion itself.', '10-15 minutes', 'Emotional Regulation', ARRAY['urge-control', 'behavior', 'DBT'],
'[{"stepNumber":1,"title":"Identify the emotion and urge","content":"What emotion are you feeling? What does it make you want to do?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Check if emotion fits the facts","content":"Is this emotion justified by the situation? Or is it more intense than warranted?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Determine opposite action","content":"What would be the opposite of your urge? If you want to isolate, the opposite is reach out. If you want to avoid, the opposite is approach.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Do it fully","content":"Commit to the opposite action completely. Half-hearted actions do not work as well.","inputRequired":false},{"stepNumber":5,"title":"Notice the shift","content":"After taking opposite action, how did your emotion change?","inputRequired":true,"inputType":"textarea"}]'),

('Temperature Change for Intense Emotion', 'Use cold water or ice to rapidly shift your nervous system.', '5-10 minutes', 'Emotional Regulation', ARRAY['crisis', 'intense-emotion', 'physiological'],
'[{"stepNumber":1,"title":"Recognize intensity","content":"Rate your emotional distress 0-10. This technique is for 8+ intensity.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Use cold","content":"Hold an ice pack to your face, splash cold water on your face, or take a cold shower. Stay with it for 30 seconds.","inputRequired":false},{"stepNumber":3,"title":"Breathe slowly","content":"While experiencing the cold, breathe slowly. This activates your dive reflex, calming your nervous system.","inputRequired":false},{"stepNumber":4,"title":"Rate intensity again","content":"After 2-3 minutes, rate your distress again. Notice any change.","inputRequired":true,"inputType":"text"},{"stepNumber":5,"title":"Reflect","content":"What did you notice in your body and emotions?","inputRequired":true,"inputType":"textarea"}]'),

('STOP Skill', 'Pause impulsive reactions with this four-step DBT technique.', '2-5 minutes', 'Emotional Regulation', ARRAY['impulse-control', 'mindfulness', 'DBT'],
'[{"stepNumber":1,"title":"S - Stop","content":"Literally freeze. Do not react. Do not move. Just stop.","inputRequired":false},{"stepNumber":2,"title":"T - Take a step back","content":"Get some space mentally. Take a breath. Count to 10. Remove yourself from the situation if needed.","inputRequired":false},{"stepNumber":3,"title":"O - Observe","content":"What is happening? What are you thinking? Feeling? What are the facts versus your interpretations?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"P - Proceed mindfully","content":"What action aligns with your values? What will make this better or worse? Choose wisely.","inputRequired":true,"inputType":"textarea"}]'),

('Progressive Muscle Relaxation', 'Systematically tense and release muscle groups to reduce physical tension.', '15-20 minutes', 'Emotional Regulation', ARRAY['relaxation', 'stress', 'somatic'],
'[{"stepNumber":1,"title":"Start with hands","content":"Clench your fists tightly for 5 seconds. Notice the tension. Then release completely for 10 seconds. Notice the difference.","inputRequired":false},{"stepNumber":2,"title":"Move through body","content":"Continue pattern through arms, shoulders, face, neck, chest, stomach, legs, feet. Tense 5 seconds, release 10 seconds.","inputRequired":false},{"stepNumber":3,"title":"Notice sensations","content":"Pay attention to the contrast between tension and relaxation. What changes?","inputRequired":false},{"stepNumber":4,"title":"Breathe throughout","content":"Keep breathing steadily. Do not hold your breath during tensing.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"How does your body feel now compared to when you started?","inputRequired":true,"inputType":"textarea"}]'),

('Emotion Surfing', 'Ride the wave of emotion without fighting it or acting on it.', '10-15 minutes', 'Emotional Regulation', ARRAY['acceptance', 'urge-surfing', 'mindfulness'],
'[{"stepNumber":1,"title":"Notice the emotion wave","content":"What emotion is rising? Give it a name. Notice it wants your attention.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Track intensity","content":"Notice the emotion is like a wave. It rises, peaks, and falls. Right now, where is it? Rising? Peaking? Falling?","inputRequired":true,"inputType":"text"},{"stepNumber":3,"title":"Stay with it","content":"Do not try to make it go away or act on urges. Just observe. Breathe. Stay present with the wave.","inputRequired":false},{"stepNumber":4,"title":"Notice the peak","content":"Emotions peak around 90 seconds if you do not feed them. Notice when it reaches its highest point.","inputRequired":false},{"stepNumber":5,"title":"Ride it down","content":"Watch it naturally decrease. Notice you survived it without acting destructively. Record what you learned.","inputRequired":true,"inputType":"textarea"}]'),

('Box Breathing', 'Regulate your nervous system with this structured breathing pattern.', '5-10 minutes', 'Emotional Regulation', ARRAY['breathing', 'anxiety', 'calm'],
'[{"stepNumber":1,"title":"Breathe in for 4","content":"Inhale slowly through your nose for 4 counts. Fill your lungs completely.","inputRequired":false},{"stepNumber":2,"title":"Hold for 4","content":"Hold your breath gently for 4 counts. Do not strain.","inputRequired":false},{"stepNumber":3,"title":"Breathe out for 4","content":"Exhale slowly through your mouth for 4 counts. Empty your lungs.","inputRequired":false},{"stepNumber":4,"title":"Hold for 4","content":"Hold empty for 4 counts before your next inhale.","inputRequired":false},{"stepNumber":5,"title":"Repeat and reflect","content":"Continue for 5-10 rounds. Notice how your body and mind feel afterward.","inputRequired":true,"inputType":"textarea"}]'),

('TIPP Skills', 'Change your body chemistry quickly during crisis using DBT techniques.', '10-15 minutes', 'Emotional Regulation', ARRAY['crisis', 'DBT', 'physiological'],
'[{"stepNumber":1,"title":"T - Temperature","content":"Use cold water on face, ice pack, or cold shower to activate dive reflex.","inputRequired":false},{"stepNumber":2,"title":"I - Intense exercise","content":"Do jumping jacks, run in place, or do burpees for 60 seconds. Get your heart rate up.","inputRequired":false},{"stepNumber":3,"title":"P - Paced breathing","content":"Breathe slowly: inhale for 5, exhale for 7. Do this for 2 minutes.","inputRequired":false},{"stepNumber":4,"title":"P - Paired muscle relaxation","content":"Tense and release muscles while breathing. Tense on inhale, release on exhale.","inputRequired":false},{"stepNumber":5,"title":"Rate and reflect","content":"Rate your distress before and after. What helped most?","inputRequired":true,"inputType":"textarea"}]'),

('Self-Soothe with Five Senses', 'Calm yourself by engaging each sense deliberately.', '15 minutes', 'Emotional Regulation', ARRAY['self-soothing', 'comfort', 'sensory'],
'[{"stepNumber":1,"title":"Vision - See something beautiful","content":"Look at art, nature, photos you love. Really take it in. What do you notice?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Hearing - Listen to soothing sounds","content":"Play calming music, nature sounds, or white noise. Let it wash over you.","inputRequired":false},{"stepNumber":3,"title":"Smell - Use pleasant scents","content":"Light a candle, use essential oils, smell coffee or flowers. Breathe deeply.","inputRequired":false},{"stepNumber":4,"title":"Taste - Enjoy a treat","content":"Slowly savor chocolate, tea, or fruit. Notice all the flavors.","inputRequired":false},{"stepNumber":5,"title":"Touch - Feel comforting textures","content":"Wrap in a soft blanket, pet an animal, or hold something smooth. Notice the sensation.","inputRequired":true,"inputType":"textarea"}]'),

('Distress Tolerance Inventory', 'Identify personalized coping strategies for different situations.', '20 minutes', 'Emotional Regulation', ARRAY['coping', 'planning', 'self-awareness'],
'[{"stepNumber":1,"title":"List healthy distractions","content":"What activities take your mind off distress? (puzzles, cleaning, walking, calling a friend)","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"List self-soothing activities","content":"What comforts you? (hot bath, favorite music, cozy space, pet)","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"List ways to improve the moment","content":"What makes now slightly better? (imagery, prayer, meaning-finding, encouragement)","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"List pros and cons","content":"When you want to act impulsively, what are reasons to wait? To tolerate?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Create your crisis kit","content":"Gather items for tough moments. What will you keep accessible?","inputRequired":true,"inputType":"textarea"}]');
