-- Add remaining 40 exercises to complete the library

INSERT INTO public.exercises (title, description, duration, category, tags, steps) VALUES

-- ACT Exercises (10)
('Values Clarification', 'Identify what truly matters to you and align your actions with your values.', '20 minutes', 'ACT', ARRAY['values', 'meaning', 'purpose'],
'[{"stepNumber":1,"title":"Explore life domains","content":"Consider these areas: relationships, work/career, personal growth, health, leisure, spirituality. Which feel most important?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Define your values","content":"For your top 3 domains, what kind of person do you want to be in each area? What qualities matter most?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Rate current alignment","content":"On a scale of 1-10, how closely are you living according to each value right now?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Identify value-aligned actions","content":"For each value, what''s one small action you could take this week to move closer to it?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Commit","content":"Choose ONE action to commit to. When will you do it?","inputRequired":true,"inputType":"text"}]'),

('Leaves on a Stream', 'Practice observing thoughts without getting caught up in them.', '10 minutes', 'ACT', ARRAY['mindfulness', 'defusion', 'acceptance'],
'[{"stepNumber":1,"title":"Get comfortable","content":"Sit comfortably and close your eyes. Take three deep breaths.","inputRequired":false},{"stepNumber":2,"title":"Imagine a stream","content":"Picture a gently flowing stream with leaves floating on the surface.","inputRequired":false},{"stepNumber":3,"title":"Place thoughts on leaves","content":"As thoughts arise, imagine placing each one on a leaf and watching it float downstream. Don''t try to control where it goes.","inputRequired":false},{"stepNumber":4,"title":"Return when distracted","content":"When you get caught up in a thought, gently notice it and return to placing thoughts on leaves.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"After 5-7 minutes, reflect: What was it like to observe your thoughts this way?","inputRequired":true,"inputType":"textarea"}]'),

('Willing Hands Exercise', 'Practice accepting the present moment through a physical posture of openness.', '5 minutes', 'ACT', ARRAY['acceptance', 'willingness', 'embodied'],
'[{"stepNumber":1,"title":"Adopt the posture","content":"Sit with your palms facing upward on your lap, arms relaxed, shoulders down.","inputRequired":false},{"stepNumber":2,"title":"Notice sensations","content":"Feel the openness of your hands. Notice any tension releasing from your shoulders and chest.","inputRequired":false},{"stepNumber":3,"title":"Breathe acceptance","content":"With each breath, say to yourself: ''I am willing to experience what I''m experiencing.''","inputRequired":false},{"stepNumber":4,"title":"Apply to difficulty","content":"Bring to mind a difficult situation. Maintain the willing hands posture as you think about it.","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Reflect","content":"How did this posture affect your relationship with the difficult situation?","inputRequired":true,"inputType":"textarea"}]'),

('Bull''s Eye Values Exercise', 'Assess how close your current actions are to your ideal values.', '15 minutes', 'ACT', ARRAY['values', 'assessment', 'goal-setting'],
'[{"stepNumber":1,"title":"Draw your bull''s eye","content":"Imagine a target with your most important value in the center. Where are you hitting now? Center (fully aligned) or outer rings (far from value)?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Identify the gap","content":"What''s the distance between where you are and where you want to be? Be honest about barriers.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Name the obstacles","content":"What gets in the way? Fear? Avoidance? Old patterns? Lack of skills?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Plan valued actions","content":"What are 3 specific actions that would move you closer to the bull''s eye?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Choose one","content":"Pick the smallest, most doable action. When will you start?","inputRequired":true,"inputType":"text"}]'),

('Passengers on the Bus', 'Visualize managing difficult thoughts and feelings while staying true to your direction.', '15 minutes', 'ACT', ARRAY['metaphor', 'values', 'control'],
'[{"stepNumber":1,"title":"You''re the bus driver","content":"Imagine you''re driving a bus toward a valued destination. Where are you heading? What matters about this direction?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Meet the passengers","content":"Difficult thoughts and feelings are passengers. They''re loud, demanding, telling you to turn around. Who are yours?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Notice the struggle","content":"What happens when you argue with these passengers or try to kick them off? Does the bus move forward?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Drive anyway","content":"Can you let the passengers be there, loud as they are, and keep driving toward what matters?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Apply it","content":"What''s one situation this week where you can ''drive the bus'' despite difficult passengers?","inputRequired":true,"inputType":"text"}]'),

('Choice Point Exercise', 'Distinguish between away moves (avoidance) and toward moves (values-based action).', '15 minutes', 'ACT', ARRAY['values', 'awareness', 'behavioral-choice'],
'[{"stepNumber":1,"title":"Identify the situation","content":"Describe a recent challenging situation or decision point.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Notice away moves","content":"What did you do (or want to do) to avoid discomfort? List all the away moves (escape, numb, procrastinate).","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Name your values","content":"In this situation, what matters most to you? What kind of person do you want to be?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Identify toward moves","content":"What actions would move you TOWARD your values, even if uncomfortable? Be specific.","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Choose","content":"Looking at your toward moves, which one will you commit to? When?","inputRequired":true,"inputType":"text"}]'),

('Expansion Technique', 'Make room for difficult emotions rather than fighting them.', '10-15 minutes', 'ACT', ARRAY['acceptance', 'emotions', 'somatic'],
'[{"stepNumber":1,"title":"Identify the feeling","content":"What difficult emotion are you experiencing right now? Name it.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Locate it in your body","content":"Where do you feel this emotion physically? Chest? Throat? Stomach? Describe the sensation.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Breathe into it","content":"Direct your breath toward that area. Imagine breathing space around the sensation, giving it room to be there.","inputRequired":false},{"stepNumber":4,"title":"Soften and allow","content":"Instead of fighting or tensing against it, soften the area. Say: ''It''s okay. I can make room for this.''","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"What happened to the intensity when you made room for it instead of fighting it?","inputRequired":true,"inputType":"textarea"}]'),

('Present Moment Grounding', 'Use your five senses to anchor yourself in the here and now.', '5 minutes', 'ACT', ARRAY['mindfulness', 'grounding', 'present-moment'],
'[{"stepNumber":1,"title":"Five things you see","content":"Name five things you can see around you right now. Really look at them.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Four things you touch","content":"Notice four things you can feel touching your body (chair, clothes, floor, air).","inputRequired":true,"inputType":"text"},{"stepNumber":3,"title":"Three things you hear","content":"Identify three sounds in your environment. Near and far.","inputRequired":true,"inputType":"text"},{"stepNumber":4,"title":"Two things you smell","content":"Notice two scents, even if subtle. Fresh air? Coffee? Fabric?","inputRequired":true,"inputType":"text"},{"stepNumber":5,"title":"One thing you taste","content":"What taste is in your mouth right now? Even if it''s just the taste of your mouth.","inputRequired":true,"inputType":"text"}]'),

('Committed Action Plan', 'Break down value-aligned goals into concrete, doable steps.', '20 minutes', 'ACT', ARRAY['values', 'action', 'goal-setting'],
'[{"stepNumber":1,"title":"State your value","content":"What value do you want to honor through this action? Why does it matter?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Set a SMART goal","content":"Create a Specific, Measurable, Achievable, Relevant, Time-bound goal aligned with this value.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Break it down","content":"What are the concrete steps to achieve this? List them in order, small to large.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Anticipate barriers","content":"What thoughts, feelings, or external obstacles might show up? How will you respond with willingness?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"First step","content":"What''s the very first action you''ll take? When specifically will you do it?","inputRequired":true,"inputType":"text"}]'),

('Noticing Exercise', 'Practice shifting attention away from thoughts to present experience.', '5-10 minutes', 'ACT', ARRAY['mindfulness', 'defusion', 'awareness'],
'[{"stepNumber":1,"title":"Notice your thoughts","content":"For one minute, notice what thoughts are showing up. Don''t try to change them, just observe.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Notice your body","content":"For one minute, bring attention to physical sensations. Breathing, tension, temperature.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Notice your surroundings","content":"For one minute, focus on what''s around you. Sights, sounds, smells. Just observe.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Practice shifting","content":"Notice you can shift your attention. Thoughts are not you. You''re the one noticing them.","inputRequired":false},{"stepNumber":5,"title":"Apply it","content":"When will you practice this noticing shift this week? What situation would benefit?","inputRequired":true,"inputType":"text"}]');

-- Continue in next message to complete remaining 30 exercises...
