-- Add next 15 exercises: Mindfulness and Journaling

INSERT INTO public.exercises (title, description, duration, category, tags, steps) VALUES

-- Mindfulness Exercises (8)
('Body Scan Meditation', 'Systematically relax your body and cultivate present-moment awareness.', '15-20 minutes', 'Mindfulness', ARRAY['relaxation', 'somatic', 'stress-relief'],
'[{"stepNumber":1,"title":"Find a comfortable position","content":"Lie down or sit comfortably. Close your eyes and take three deep breaths.","inputRequired":false},{"stepNumber":2,"title":"Scan your feet","content":"Bring awareness to your feet. Notice any sensations - warmth, tingling, pressure. Breathe into this area.","inputRequired":false},{"stepNumber":3,"title":"Move up slowly","content":"Gradually move your attention up through legs, hips, abdomen, chest, arms, hands, shoulders, neck, and head. Spend 30 seconds on each area.","inputRequired":false},{"stepNumber":4,"title":"Notice without judging","content":"If you find tension, simply notice it. Don''t try to fix it. Just observe with curiosity.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"How do you feel now compared to when you started? What did you notice?","inputRequired":true,"inputType":"textarea"}]'),

('Mindful Breathing', 'Use your breath as an anchor to the present moment.', '5-10 minutes', 'Mindfulness', ARRAY['anxiety', 'stress-relief', 'grounding'],
'[{"stepNumber":1,"title":"Find your breath","content":"Sit comfortably. Close your eyes. Notice where you feel your breath most - nose, chest, or belly.","inputRequired":false},{"stepNumber":2,"title":"Count your breaths","content":"Count each exhale from 1 to 10. When you reach 10, start over. If you lose count, gently return to 1.","inputRequired":false},{"stepNumber":3,"title":"Notice wandering","content":"Your mind will wander - that''s normal. Each time you notice, gently return attention to breath. No judgment.","inputRequired":false},{"stepNumber":4,"title":"Extend awareness","content":"After a few minutes, expand awareness to include sounds, sensations, while keeping breath in the background.","inputRequired":false},{"stepNumber":5,"title":"Close mindfully","content":"Take three deep breaths. Open your eyes slowly. What do you notice about your state of mind?","inputRequired":true,"inputType":"textarea"}]'),

('RAIN Technique', 'Work through difficult emotions with compassion using Recognize, Allow, Investigate, Nurture.', '10-15 minutes', 'Mindfulness', ARRAY['emotions', 'self-compassion', 'emotional-regulation'],
'[{"stepNumber":1,"title":"Recognize what''s happening","content":"Name the difficult emotion or experience. What''s present right now?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Allow it to be there","content":"Stop fighting it. Say ''yes'' to the experience as it is, even if uncomfortable. Breathe.","inputRequired":false},{"stepNumber":3,"title":"Investigate with kindness","content":"Where do you feel this in your body? What beliefs or thoughts are present? Explore with curiosity, not judgment.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Nurture with self-compassion","content":"Place a hand on your heart. What would you say to a dear friend feeling this way? Offer yourself those same words.","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Notice the shift","content":"After offering compassion, what''s different? Even small shifts matter.","inputRequired":true,"inputType":"textarea"}]'),

('Loving-Kindness Meditation', 'Cultivate compassion for yourself and others through traditional phrases.', '10-15 minutes', 'Mindfulness', ARRAY['self-compassion', 'relationships', 'positivity'],
'[{"stepNumber":1,"title":"Start with yourself","content":"Sit comfortably. Repeat silently: ''May I be safe. May I be healthy. May I be happy. May I live with ease.'' Notice what arises.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Extend to someone easy","content":"Picture someone you care about. Repeat: ''May you be safe. May you be healthy. May you be happy. May you live with ease.''","inputRequired":false},{"stepNumber":3,"title":"Include a neutral person","content":"Think of someone you don''t know well (cashier, neighbor). Offer them the same phrases.","inputRequired":false},{"stepNumber":4,"title":"Include someone difficult","content":"If you''re ready, picture someone challenging. Offer them the phrases (even if it feels hard).","inputRequired":false},{"stepNumber":5,"title":"Extend to all beings","content":"Finish by extending wishes to all beings everywhere. Notice how this practice affected you.","inputRequired":true,"inputType":"textarea"}]'),

('Mountain Meditation', 'Cultivate stability and groundedness through visualization.', '10 minutes', 'Mindfulness', ARRAY['resilience', 'grounding', 'stability'],
'[{"stepNumber":1,"title":"Sit like a mountain","content":"Sit with dignity, spine straight. Imagine yourself as a mountain - solid, stable, grounded.","inputRequired":false},{"stepNumber":2,"title":"Visualize the mountain","content":"Picture a mountain in detail. Its peak, slopes, base. Notice its stillness despite weather changing around it.","inputRequired":false},{"stepNumber":3,"title":"Become the mountain","content":"You are this mountain. Thoughts and emotions are like weather - passing clouds, storms, sunshine. You remain.","inputRequired":false},{"stepNumber":4,"title":"Notice the weather","content":"As thoughts and feelings arise (your ''weather''), notice them passing while you remain steady like the mountain.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"What was it like to remain stable while inner weather changed? What did you learn?","inputRequired":true,"inputType":"textarea"}]'),

('Walking Meditation', 'Practice mindfulness through slow, deliberate movement.', '10-15 minutes', 'Mindfulness', ARRAY['movement', 'grounding', 'embodied'],
'[{"stepNumber":1,"title":"Find your path","content":"Choose a 10-15 foot path where you can walk back and forth safely.","inputRequired":false},{"stepNumber":2,"title":"Begin slowly","content":"Stand at one end. Feel your feet on the ground. Begin walking very slowly, noticing each sensation.","inputRequired":false},{"stepNumber":3,"title":"Focus on sensations","content":"Notice: lifting foot, moving forward, placing down, shifting weight. Just these physical sensations.","inputRequired":false},{"stepNumber":4,"title":"Return when wandering","content":"Mind will wander. When it does, gently return attention to the soles of your feet.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"After 10 minutes, stand still. How present do you feel? What did walking slowly reveal?","inputRequired":true,"inputType":"textarea"}]'),

('Noting Practice', 'Label mental experiences to create space from them.', '10 minutes', 'Mindfulness', ARRAY['awareness', 'defusion', 'meditation'],
'[{"stepNumber":1,"title":"Begin with breath","content":"Sit comfortably, eyes closed. Focus on your breath.","inputRequired":false},{"stepNumber":2,"title":"Note what arises","content":"When something pulls your attention, label it simply: ''thinking'', ''feeling'', ''hearing'', ''planning''.","inputRequired":false},{"stepNumber":3,"title":"Keep it simple","content":"Don''t analyze. Just note and return to breath. Note, return. Note, return.","inputRequired":false},{"stepNumber":4,"title":"Notice patterns","content":"After a few minutes, what''s most common? Thinking? Planning? Judging? Just observe.","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Close gently","content":"Stop noting. Return to pure breath awareness for a minute. Then reflect on what you noticed.","inputRequired":true,"inputType":"textarea"}]'),

('Mindful Eating Practice', 'Eat a single food item with complete presence and awareness.', '10 minutes', 'Mindfulness', ARRAY['eating', 'presence', 'sensory'],
'[{"stepNumber":1,"title":"Choose your food","content":"Pick something small (raisin, piece of chocolate, strawberry). Hold it in your hand.","inputRequired":false},{"stepNumber":2,"title":"Observe it","content":"Look at it as if you''ve never seen it before. Notice color, texture, shape. Spend 30 seconds just looking.","inputRequired":false},{"stepNumber":3,"title":"Engage other senses","content":"Smell it. Touch it. Listen as you manipulate it. Bring full attention to each sense.","inputRequired":false},{"stepNumber":4,"title":"Taste slowly","content":"Place it in your mouth but don''t chew yet. Notice the impulse to chew. Then chew slowly, noticing each sensation.","inputRequired":false},{"stepNumber":5,"title":"Reflect","content":"How was this different from how you usually eat? What did you notice?","inputRequired":true,"inputType":"textarea"}]');

-- Continue with next batch in following migration...
