-- Add journaling exercises with proper escaping

INSERT INTO public.exercises (title, description, duration, category, tags, steps) VALUES

-- Journaling Exercises (12)
('Gratitude Journal', 'Cultivate appreciation by noting three good things daily.', '10 minutes', 'Journaling', ARRAY['gratitude', 'positivity', 'mood'],
'[{"stepNumber":1,"title":"Find three things","content":"What are three specific things you are grateful for today? They can be big or small.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Go deeper","content":"For each one, write WHY you are grateful. What would life be like without it?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Notice sensations","content":"As you write, notice how gratitude feels in your body. Warmth? Openness? Lightness?","inputRequired":true,"inputType":"textarea"}]'),

('Emotion Journal', 'Track and process your emotional experiences with structure.', '10-15 minutes', 'Journaling', ARRAY['emotions', 'awareness', 'tracking'],
'[{"stepNumber":1,"title":"Name the emotion","content":"What emotion(s) did you feel today? List them all, even subtle ones.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Rate intensity","content":"Rate each emotion 0-10. No judgment, just observation.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Find the trigger","content":"What situation, thought, or interaction sparked each emotion?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Notice your response","content":"How did you react to each emotion? Avoid? Express? Suppress?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Reflect on patterns","content":"Looking at your entries over time, what patterns emerge?","inputRequired":true,"inputType":"textarea"}]'),

('Stream of Consciousness Writing', 'Let thoughts flow onto paper without filtering or editing.', '15 minutes', 'Journaling', ARRAY['processing', 'awareness', 'expressive'],
'[{"stepNumber":1,"title":"Set a timer","content":"Set a timer for 15 minutes. Your only rule: do not stop writing until time is up.","inputRequired":false},{"stepNumber":2,"title":"Write everything","content":"Write whatever comes to mind. No editing, no crossing out, no judgment. Just write.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Keep the pen moving","content":"If you get stuck, write: I do not know what to write - until something else comes.","inputRequired":false},{"stepNumber":4,"title":"Do not reread yet","content":"When time is up, close your journal without rereading. Let it sit for a few hours.","inputRequired":false},{"stepNumber":5,"title":"Review later","content":"Later or tomorrow, reread. What themes emerge? What surprised you?","inputRequired":true,"inputType":"textarea"}]'),

('Morning Pages', 'Clear mental clutter with three pages of longhand writing each morning.', '20-30 minutes', 'Journaling', ARRAY['clarity', 'creativity', 'routine'],
'[{"stepNumber":1,"title":"Write first thing","content":"Before phone, coffee, or anything else, grab your journal. Write three full pages longhand.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Write everything","content":"Complaints, to-dos, dreams, worries - all of it. Do not censor or try to make it good.","inputRequired":false},{"stepNumber":3,"title":"Establish a routine","content":"This works best as a daily practice. What time each morning will you write?","inputRequired":true,"inputType":"text"},{"stepNumber":4,"title":"Notice resistance","content":"If you resist this practice, that is normal. What stories does your mind tell you about writing?","inputRequired":true,"inputType":"textarea"}]'),

('Letter to Your Younger Self', 'Process past experiences with compassion and wisdom.', '20 minutes', 'Journaling', ARRAY['self-compassion', 'healing', 'reflection'],
'[{"stepNumber":1,"title":"Choose an age","content":"Pick a younger version of yourself who was struggling. How old were they? What was happening?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Write the letter","content":"Write a letter to that younger you. What do they need to hear? What wisdom can you offer now?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Acknowledge the pain","content":"Validate their struggle. What do you understand now about that time?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Offer reassurance","content":"What would you want them to know about the future? About their strength?","inputRequired":true,"inputType":"textarea"}]'),

('Worry Dump Journal', 'Externalize anxious thoughts to reduce their mental burden.', '10 minutes', 'Journaling', ARRAY['anxiety', 'worry', 'processing'],
'[{"stepNumber":1,"title":"Set a timer","content":"Give yourself 10 minutes. You are going to dump every worry out of your head.","inputRequired":false},{"stepNumber":2,"title":"List all worries","content":"Write every worry, big and small. Racing thoughts, nagging concerns, catastrophic scenarios - all of it.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Do not analyze","content":"Just list. Do not try to solve or evaluate yet. Get it all on paper.","inputRequired":false},{"stepNumber":4,"title":"Close the journal","content":"When time is up, close the journal. Tell yourself: I have acknowledged these. They can stay on the paper for now.","inputRequired":false},{"stepNumber":5,"title":"Return later","content":"After a few hours, return to the list. Which worries still feel urgent? Which have faded?","inputRequired":true,"inputType":"textarea"}]'),

('Best Possible Self Visualization', 'Imagine and write about your ideal future to boost hope and motivation.', '15-20 minutes', 'Journaling', ARRAY['hope', 'motivation', 'future'],
'[{"stepNumber":1,"title":"Set the scene","content":"Imagine yourself 5-10 years from now, everything going as well as it possibly could. Where are you? What is your life like?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Describe in detail","content":"Write about your best possible self in specific, vivid detail. What do you see, hear, feel?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Include all domains","content":"Describe relationships, work, health, personal growth. Be specific and optimistic.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Identify steps","content":"What actions could move you toward this vision? List concrete next steps.","inputRequired":true,"inputType":"textarea"}]'),

('Unsent Letter', 'Process difficult relationships or unresolved feelings through writing.', '20 minutes', 'Journaling', ARRAY['relationships', 'processing', 'closure'],
'[{"stepNumber":1,"title":"Choose a recipient","content":"Who would you write to? This letter will never be sent - total freedom to express.","inputRequired":true,"inputType":"text"},{"stepNumber":2,"title":"Write uncensored","content":"Say everything you need to say. Anger, hurt, gratitude, confusion - all of it. Hold nothing back.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Express needs","content":"What did you need from this person? What do you still need? Write it clearly.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Find closure","content":"How do you want to end this letter? What would bring you peace?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Decide its fate","content":"You can keep it, tear it up, or burn it. The writing itself is the healing.","inputRequired":false}]'),

('Wins Journal', 'Counter negativity bias by documenting daily successes.', '10 minutes', 'Journaling', ARRAY['positivity', 'self-esteem', 'achievement'],
'[{"stepNumber":1,"title":"List your wins","content":"What went well today? List everything - big accomplishments and tiny victories.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Include the mundane","content":"Got out of bed? Made breakfast? Sent one email? These count. Write them down.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Note your role","content":"For each win, what did YOU do to make it happen? Acknowledge your effort and agency.","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Feel it","content":"Pause and actually feel good about these wins. Let yourself experience pride or satisfaction.","inputRequired":false}]'),

('Five-Minute Journal', 'Quick daily practice combining gratitude, intention, and reflection.', '5 minutes', 'Journaling', ARRAY['routine', 'gratitude', 'reflection'],
'[{"stepNumber":1,"title":"Morning: Gratitude","content":"I am grateful for: (list 3 things)","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Morning: Todays goals","content":"What would make today great? (list 3)","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Morning: Daily affirmation","content":"I am... (complete the sentence)","inputRequired":true,"inputType":"text"},{"stepNumber":4,"title":"Evening: Highlights","content":"Amazing things that happened today: (list 3)","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Evening: Improvement","content":"How could I have made today better?","inputRequired":true,"inputType":"textarea"}]'),

('Values Journaling', 'Explore what matters most and whether your life aligns.', '15 minutes', 'Journaling', ARRAY['values', 'alignment', 'reflection'],
'[{"stepNumber":1,"title":"List your top values","content":"What matters most to you? (courage, connection, creativity, justice, etc.) List 5-7 core values.","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Define them","content":"For each value, what does it mean to YOU? How would you explain it?","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Rate alignment","content":"For each value, rate 1-10: How aligned is your life with this value right now?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Explore gaps","content":"Where are the biggest gaps? Why? What gets in the way?","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Plan value-aligned action","content":"Choose one value. What is one action this week that honors it?","inputRequired":true,"inputType":"text"}]'),

('Dialogue with a Part', 'Have a written conversation with different parts of yourself.', '15-20 minutes', 'Journaling', ARRAY['self-awareness', 'inner-work', 'parts'],
'[{"stepNumber":1,"title":"Identify the part","content":"Which part of you wants attention? The anxious part? Critical part? Playful part?","inputRequired":true,"inputType":"textarea"},{"stepNumber":2,"title":"Give it a voice","content":"Write from that part perspective in first person. Let it speak fully.","inputRequired":true,"inputType":"textarea"},{"stepNumber":3,"title":"Respond with curiosity","content":"Now write from your centered self. Ask the part: What do you need? What are you protecting me from?","inputRequired":true,"inputType":"textarea"},{"stepNumber":4,"title":"Continue the dialogue","content":"Let the part respond. Keep the conversation going until you feel complete.","inputRequired":true,"inputType":"textarea"},{"stepNumber":5,"title":"Thank the part","content":"End by thanking this part for sharing. What did you learn?","inputRequired":true,"inputType":"textarea"}]');
