-- Add 30+ curated stories from diverse cultural traditions

-- Buddhist Stories (6)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('The Second Arrow', 'Buddha taught: when hit by an arrow, we suffer. But we shoot ourselves with a second arrow—our reaction to the pain. The first arrow is unavoidable; the second is optional.', 'Buddhist Teaching', 'Buddhist', ARRAY['suffering', 'acceptance', 'rumination'], 'Our suffering often comes from our resistance to pain, not the pain itself.'),
('The Monk and the Samurai', 'A samurai demanded a monk explain heaven and hell. The monk insulted him. Enraged, the samurai drew his sword. The monk said: "That is hell." The samurai understood, sheathed his sword, and bowed. The monk said: "That is heaven."', 'Zen Story', 'Buddhist', ARRAY['anger', 'awareness', 'transformation'], 'Heaven and hell are states of mind we create through our reactions.'),
('The Muddy Road', 'Two monks encountered a woman unable to cross a muddy road. One carried her across. Hours later, the other monk complained: "We aren''t supposed to touch women!" The first replied: "I put her down hours ago. Why are you still carrying her?"', 'Zen Parable', 'Buddhist', ARRAY['letting-go', 'rumination', 'rigidity'], 'We often carry burdens long after we could have released them.'),
('The Empty Cup', 'A professor visited a Zen master. The master poured tea until the cup overflowed. "Stop!" said the professor. The master replied: "Like this cup, you are full of your own opinions. How can I show you Zen unless you first empty your cup?"', 'Zen Teaching', 'Buddhist', ARRAY['openness', 'ego', 'learning'], 'We can''t learn new things while clinging to old beliefs and certainties.'),
('Is That So?', 'When a girl became pregnant and blamed Zen master Hakuin, he said only: "Is that so?" He raised the baby without complaint. A year later, the girl confessed the real father. Her parents apologized profusely. Hakuin said only: "Is that so?"', 'Zen Story', 'Buddhist', ARRAY['equanimity', 'reputation', 'non-attachment'], 'True peace comes from not clinging to praise or fleeing from blame.'),
('The Two Wolves', 'An elder told his grandson: "Inside me are two wolves fighting. One is anger, envy, regret, greed, arrogance. The other is joy, peace, love, hope, humility, kindness." The grandson asked: "Which wolf wins?" The elder replied: "The one I feed."', 'Cherokee Wisdom', 'Native American', ARRAY['choice', 'emotion', 'intention'], 'We become what we nurture; our attention shapes our character.');

-- Sufi Stories (5)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('The Guest House', 'Rumi wrote: "This being human is a guest house. Every morning a new arrival. A joy, a depression, a meanness... Welcome and entertain them all! Even if they''re a crowd of sorrows... Be grateful for whoever comes, because each has been sent as a guide from beyond."', 'Rumi', 'Persian', ARRAY['acceptance', 'emotions', 'hospitality'], 'All emotions have wisdom to teach us if we welcome them rather than resist them.'),
('The Elephant in the Dark', 'People touched different parts of an elephant in darkness—one felt the trunk, one the leg, one the ear—and each insisted they knew what an elephant was. But none saw the whole truth.', 'Rumi', 'Persian', ARRAY['perspective', 'truth', 'humility'], 'We each see only part of reality; humility and dialogue reveal the bigger picture.'),
('Nasruddin''s Keys', 'People found Nasruddin searching for his keys under a streetlamp. "Where did you lose them?" "In my house." "Then why search here?" "Because the light is better here!"', 'Nasruddin Tales', 'Sufi', ARRAY['avoidance', 'comfort-zone', 'truth'], 'We often look for answers where it''s comfortable rather than where the real problem lies.'),
('Nasruddin''s Donkey', 'Nasruddin was searching for his donkey while sitting on it. Someone pointed this out. He said: "Thank God! If I had found the donkey before I found myself on it, I would have lost myself too!"', 'Nasruddin Tales', 'Sufi', ARRAY['awareness', 'searching', 'perspective'], 'Sometimes what we''re desperately seeking is already present; we need awareness, not achievement.'),
('The Ocean and the Wave', 'A wave was terrified it would crash and disappear. Another wave said: "You don''t understand. You''re not just a wave—you''re water. You were never separate from the ocean."', 'Sufi Teaching', 'Sufi', ARRAY['identity', 'fear', 'unity'], 'Our fear of death and loss comes from identifying with our temporary form rather than our eternal essence.');

-- Stoic Stories (5)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('Marcus Aurelius'' Rain', 'Emperor Marcus Aurelius wrote in his journal during military campaigns: "Rain is neither good nor bad. It simply is. My judgment makes it so." He ruled the Roman Empire while facing plague, war, and betrayal—yet chose gratitude.', 'Marcus Aurelius - Meditations', 'Stoic', ARRAY['perspective', 'acceptance', 'judgment'], 'Events are neutral; our judgments create our suffering or peace.'),
('Epictetus'' Broken Pot', 'Born a slave, Epictetus was crippled when his master broke his leg. He became one of history''s greatest philosophers. He taught: "It''s not what happens to you, but how you react that matters." He turned slavery into freedom through his mind.', 'Epictetus', 'Stoic', ARRAY['resilience', 'control', 'freedom'], 'External circumstances don''t determine our inner freedom; our responses do.'),
('Seneca''s Fire', 'When Seneca lost all his possessions in a fire, he wrote: "I have lost nothing because all that was not mine. My mind is my own and cannot be taken." He rebuilt his philosophy, not his possessions.', 'Seneca', 'Stoic', ARRAY['loss', 'attachment', 'self'], 'What truly belongs to us—our character, our choices—cannot be taken away.'),
('The Obstacle Is the Way', 'Marcus Aurelius wrote: "The impediment to action advances action. What stands in the way becomes the way." Every obstacle he faced—from plague to betrayal—became an opportunity to practice virtue.', 'Marcus Aurelius', 'Stoic', ARRAY['obstacles', 'opportunity', 'growth'], 'Our greatest challenges become our greatest teachers if we learn from them.'),
('Epictetus and the Lamp', 'After Epictetus became famous, someone stole his iron lamp. He replaced it with an earthenware one, saying: "Tomorrow I will be the owner of an earthenware lamp and the thief will still be a thief. I got the better bargain."', 'Epictetus', 'Stoic', ARRAY['theft', 'character', 'peace'], 'External losses are temporary; loss of character is permanent. Guard what truly matters.');

-- Real Historical Figures (8)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('Viktor Frankl''s Choice', 'In Auschwitz concentration camp, Viktor Frankl lost his family, his manuscript, everything. Yet he realized: "Everything can be taken from a man but one thing: the last of human freedoms—to choose one''s attitude." He survived by finding meaning in suffering.', 'Viktor Frankl - Man''s Search for Meaning', 'Modern', ARRAY['meaning', 'suffering', 'choice'], 'Even in the worst circumstances, we retain the freedom to choose our response.'),
('Mandela''s Forgiveness', 'Nelson Mandela spent 27 years in prison. On his release, he invited his former prison guard to his presidential inauguration. He said: "Resentment is like drinking poison and hoping it will kill your enemies." He chose reconciliation over revenge.', 'Nelson Mandela', 'African', ARRAY['forgiveness', 'freedom', 'resentment'], 'Forgiveness frees the forgiver even more than the forgiven; resentment is self-inflicted prison.'),
('Maya Angelou Rises', 'Maya Angelou was raped as a child and stopped speaking for five years. She became one of history''s greatest poets. She wrote: "You may shoot me with your words... But still, like dust, I''ll rise." Trauma didn''t end her voice; it deepened it.', 'Maya Angelou', 'African American', ARRAY['trauma', 'resilience', 'voice'], 'Our wounds can become the source of our greatest strength and expression.'),
('Beethoven''s Symphony', 'Beethoven went deaf—a death sentence for a composer. In complete silence, he composed his greatest work, the Ninth Symphony. He never heard it performed, yet gave the world eternal beauty from his darkness.', 'Ludwig van Beethoven', 'European', ARRAY['disability', 'creation', 'persistence'], 'Our limitations can birth our greatest contributions if we persist despite them.'),
('Malala''s Voice', 'After being shot in the head by the Taliban for advocating girls'' education, Malala Yousafzai could have retreated in fear. Instead, she spoke at the UN on her 16th birthday: "One child, one teacher, one book, one pen can change the world."', 'Malala Yousafzai', 'Pakistani', ARRAY['courage', 'education', 'voice'], 'Speaking truth despite danger can change the world; fear only wins when we are silent.'),
('Harriet Tubman''s Returns', 'After escaping slavery, Harriet Tubman returned to the South 19 times to free others, risking her life each time. She said: "I could have freed thousands more if only they knew they were slaves." Freedom requires awareness and courage.', 'Harriet Tubman', 'African American', ARRAY['freedom', 'courage', 'service'], 'True freedom means helping others find theirs; awareness of our chains is the first step to breaking them.'),
('Frida Kahlo''s Art', 'Frida Kahlo suffered a devastating bus accident at 18, enduring 30+ surgeries and chronic pain. She painted herself back together, creating art that transformed suffering into beauty. "I paint myself because I am so often alone and I am the subject I know best."', 'Frida Kahlo', 'Mexican', ARRAY['pain', 'art', 'self-expression'], 'We can transform suffering into beauty through creative expression; our pain can become our art.'),
('Helen Keller''s World', 'Deaf and blind from infancy, Helen Keller graduated from Harvard, wrote 14 books, and became a powerful activist. She said: "The only thing worse than being blind is having sight but no vision." She saw more than most sighted people.', 'Helen Keller', 'American', ARRAY['disability', 'perspective', 'vision'], 'Physical limitations don''t limit vision; many who can see lack the vision to truly live.');

-- African Wisdom (4)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('Ubuntu - I Am Because We Are', 'In South Africa, a researcher placed food near a tree and told children the first to reach it would win it all. Instead, they held hands and ran together, then sat and shared. They explained: "Ubuntu—how can one be happy when others are sad?"', 'African Wisdom', 'African', ARRAY['connection', 'community', 'compassion'], 'Our individual happiness is inseparable from others'' wellbeing; we rise together or not at all.'),
('The Wisdom Tree', 'An African proverb teaches: "Wisdom is like a baobab tree; no one person can embrace it alone." The baobab''s trunk is too wide for individual arms. Wisdom requires the embrace of community.', 'African Proverb', 'African', ARRAY['wisdom', 'community', 'humility'], 'No single person holds all wisdom; we need each other to see the full truth.'),
('Anansi Teaches His Children', 'Anansi the spider asked his children what they''d choose: wisdom or wealth. Most chose wealth. The youngest said: "With wisdom, I can find wealth. With wealth, I cannot find wisdom." Anansi smiled—this child understood.', 'West African Folk Tale', 'African', ARRAY['wisdom', 'values', 'priorities'], 'Wisdom generates all good things; without it, wealth brings only temporary satisfaction.'),
('The Drum That Beats By Itself', 'An African tale tells of a magical drum that beats by itself when the village lives in harmony. When conflict arose, the drum fell silent. The villagers realized: the drum never had magic—their unity did.', 'African Folk Tale', 'African', ARRAY['harmony', 'community', 'unity'], 'What appears magical in community is simply the natural result of living in harmony.');

-- Greek Philosophy (3)
INSERT INTO public.stories (title, content, source, cultural_origin, tags, why_matters) VALUES
('Diogenes and Alexander', 'Alexander the Great found philosopher Diogenes lying in the sun. "I am Alexander the Great. Ask anything." Diogenes replied: "Stand out of my sunlight." Alexander said: "If I were not Alexander, I would be Diogenes." True power needs nothing.', 'Diogenes the Cynic', 'Greek', ARRAY['simplicity', 'power', 'contentment'], 'The person who needs nothing has more power than the person who rules empires.'),
('Plato''s Cave', 'Plato described prisoners chained in a cave, seeing only shadows on the wall, believing shadows were reality. One breaks free, sees the sun, and returns to free others. But they prefer familiar shadows to blinding truth.', 'Plato - The Republic', 'Greek', ARRAY['truth', 'illusion', 'awakening'], 'We resist truth that challenges our comfortable illusions; awakening is often unwelcome.'),
('Pyrrhus and Cineas', 'Pyrrhus planned to conquer Rome, then Sicily, then Africa. His advisor Cineas asked: "Then what?" "We will rest and be happy." "Why not rest and be happy now?" We postpone happiness for achievements that promise the happiness we already could have.', 'Plutarch', 'Greek', ARRAY['happiness', 'postponement', 'achievement'], 'We chase achievements believing they''ll bring happiness we could choose right now.');