// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wytzlvaiulrsrjbtwglk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dHpsdmFpdWxyc3JqYnR3Z2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjAzOTksImV4cCI6MjA3Njc5NjM5OX0.f_x0ee1rBAgqpeAn2_qqnAbecYL6_Kd2Nk0RWav0OWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});